server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://ep-billowing-silence-b30jkujt-pooler.c-4.ap-southeast-1.aws.neon.tech/auth_db?sslmode=require
    username: neondb_owner
    password: npg_R7gOhQBkDUx4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: auth

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 5000ms

# JWT Configuration
jwt:
  # Base64-encoded secret — generate with: openssl rand -base64 32
  secret: 5K9mRzT8sW3vY1nJ7pQ4xB6cL2hF0eA9dG8uN5oX3yV7wZ1iM4kP6
  access-token-expiration: 3600000    # 1 hour in ms
  refresh-token-expiration: 604800000 # 7 days in ms

openapi:
  service:
    title: Auth Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO
    com.fooddelivery.auth: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html