server:
  port: 8080

spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive   # Bắt buộc Netty khởi động, không phụ thuộc IDE

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info