server:
  port: 8085

spring:
  application:
    name: payment-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://ep-billowing-silence-b30jkujt-pooler.c-4.ap-southeast-1.aws.neon.tech/payment_db?sslmode=require
    username: neondb_owner
    password: npg_R7gOhQBkDUx4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: payment

  flyway:
    enabled: false
    url: jdbc:postgresql://ep-billowing-silence-b30jkujt-pooler.c-4.ap-southeast-1.aws.neon.tech/payment_db?sslmode=require
    user: neondb_owner
    password: npg_R7gOhQBkDUx4
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    schemas: payment
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fooddelivery.payment.dto.event.OrderEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

openapi:
  service:
    title: Payment Service API
    version: 1.0.0

payment:
  sepay:
    bank-name: ${SEPAY_BANK_NAME:MBBank}
    account-number: ${SEPAY_ACCOUNT_NUMBER:025452790502}
    account-holder: ${SEPAY_ACCOUNT_HOLDER:NGUYEN THAI AN}
    api-token: ${SEPAY_API_TOKEN:}

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

logging:
  level:
    root: INFO
    web: INFO
    org.flywaydb: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html