spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true

#openapi:
#  service:
#    api-docs: support-service
#    server: http://localhost:${server.port}
#    title: support service
#    version: 1.0.0
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true