server:
  port: 8083

spring:
  application:
    name: order-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://ep-billowing-silence-b30jkujt-pooler.c-4.ap-southeast-1.aws.neon.tech/order_db?sslmode=require
    username: neondb_owner
    password: npg_R7gOhQBkDUx4
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orders

  flyway:
    enabled: false
    url: jdbc:postgresql://ep-billowing-silence-b30jkujt-pooler.c-4.ap-southeast-1.aws.neon.tech/order_db?sslmode=require
    user: neondb_owner
    password: npg_R7gOhQBkDUx4
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    schemas: orders
    locations: classpath:db/migration

  # Cấu hình MongoDB cho Review Comments (review_comment_db)
  data:
    mongodb:
      uri: mongodb+srv://lananhhii121_db_user:lananh123@delivery-system.1fh7sey.mongodb.net/review_comment_db?retryWrites=true&w=majority&appName=Delivery-system
      auto-index-creation: true

openapi:
  service:
    title: Order Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO
    org.flywaydb: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html