server:
  port: 8087

spring:
  application:
    name: analytics-service
  profiles:
    active: dev

  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: analytics

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    schemas: analytics
    locations: classpath:db/migration

openapi:
  service:
    title: Analytics Service API
    version: 1.0.0

logging:
  level:
    root: INFO
    web: INFO
    org.flywaydb: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html